import { existsSync, mkdirSync, writeFileSync, readFileSync, rmSync } from "fs";
import { join } from "path";
import {
  defineSchema,
  EnvValidator,
  EnvAggregateError,
} from "../../src/index.js";
import type { SchemaDefinition } from "../../src/index.js";

const FIXTURES_DIR = join(__dirname, ".fixtures");

function setupFixture(name: string) {
  const dir = join(FIXTURES_DIR, name);
  if (existsSync(dir)) rmSync(dir, { recursive: true });
  mkdirSync(dir, { recursive: true });
  return dir;
}

function writeJson(dir: string, filename: string, content: object) {
  writeFileSync(join(dir, filename), JSON.stringify(content, null, 2));
}

beforeAll(() => {
  if (!existsSync(FIXTURES_DIR)) mkdirSync(FIXTURES_DIR, { recursive: true });
});

afterAll(() => {
  if (existsSync(FIXTURES_DIR)) rmSync(FIXTURES_DIR, { recursive: true });
});

describe("Schema loading from JSON", () => {
  test("loads a valid JSON schema and validates env", () => {
    const dir = setupFixture("json-schema");
    const schema: SchemaDefinition = {
      APP_PORT: { type: "port", default: 3000 },
      APP_NAME: { type: "string", default: "testapp" },
    };
    writeJson(dir, "schema.json", schema);

    const loaded: SchemaDefinition = JSON.parse(
      readFileSync(join(dir, "schema.json"), "utf-8"),
    );
    const v = new EnvValidator(loaded);
    const result = v.validate({});
    expect(result.APP_PORT).toBe(3000);
    expect(result.APP_NAME).toBe("testapp");
  });

  test("JSON schema with required fields throws on empty env", () => {
    const schema: SchemaDefinition = {
      API_KEY: { type: "string", required: true },
    };

    const v = new EnvValidator(schema);
    expect(() => v.validate({})).toThrow(EnvAggregateError);
  });
});

describe("End-to-end validation workflow", () => {
  test("full validation pipeline: define schema, validate env, get typed result", () => {
    const schema = defineSchema({
      NODE_ENV: {
        type: "string",
        enum: ["development", "production", "test"],
        default: "development",
      },
      PORT: { type: "port", default: 3000 },
      DB_URL: { type: "url", required: true },
      DEBUG: { type: "boolean", default: false },
      MAX_RETRIES: { type: "number", min: 0, max: 10, default: 3 },
    });

    const v = new EnvValidator(schema);
    const result = v.validate({
      NODE_ENV: "production",
      PORT: "8080",
      DB_URL: "https://db.example.com/mydb",
      DEBUG: "true",
      MAX_RETRIES: "5",
    });

    expect(result.NODE_ENV).toBe("production");
    expect(result.PORT).toBe(8080);
    expect(result.DB_URL).toBe("https://db.example.com/mydb");
    expect(result.DEBUG).toBe(true);
    expect(result.MAX_RETRIES).toBe(5);
  });

  test("validation collects all errors at once", () => {
    const schema = defineSchema({
      PORT: { type: "port", required: true },
      EMAIL: { type: "email", required: true },
      API_URL: { type: "url", required: true },
    });

    const v = new EnvValidator(schema);
    try {
      v.validate({
        PORT: "invalid",
        EMAIL: "not-email",
        API_URL: "not-url",
      });
      throw new Error("should have thrown");
    } catch (err: any) {
      expect(err).toBeInstanceOf(EnvAggregateError);
      expect(err.errors).toHaveLength(3);
      const keys = err.errors.map((e: any) => e.key);
      expect(keys).toContain("PORT");
      expect(keys).toContain("EMAIL");
      expect(keys).toContain("API_URL");
    }
  });

  test("strict mode combined with grouped variables works correctly", () => {
    const schema = defineSchema({
      APP_NAME: { type: "string", required: true },
      DATABASE: {
        type: "object",
        properties: {
          HOST: { type: "string", default: "localhost" },
          PORT: { type: "port", default: 5432 },
        },
      },
    });

    const v = new EnvValidator(schema, { strict: true });
    const result = v.validate({
      APP_NAME: "myapp",
      DATABASE_HOST: "db.prod.com",
      DATABASE_PORT: "5433",
    });

    expect(result.APP_NAME).toBe("myapp");
    expect(result.DATABASE.HOST).toBe("db.prod.com");
    expect(result.DATABASE.PORT).toBe(5433);
  });
});

describe("Sync command output generation", () => {
  test("generates .env.example content from schema", () => {
    const schema: SchemaDefinition = {
      APP_NAME: { type: "string", default: "MyApp", docs: "Application name" },
      PORT: { type: "port", default: 3000, docs: "Server port" },
      DB_PASSWORD: {
        type: "string",
        sensitive: true,
        docs: "Database password",
      },
    };

    const lines: string[] = [];
    lines.push("# Auto-generated by dotenv-gad");
    lines.push("");

    for (const [key, rule] of Object.entries(schema)) {
      if (rule.sensitive) {
        lines.push(`# ${key} - [SENSITIVE - not included]`);
        continue;
      }
      if (rule.docs) lines.push(`# ${rule.docs}`);
      lines.push(`# Type: ${rule.type}`);
      if (rule.default !== undefined) {
        lines.push(`${key}=${rule.default}`);
      } else {
        lines.push(`${key}=`);
      }
      lines.push("");
    }

    const content = lines.join("\n");
    expect(content).toContain("APP_NAME=MyApp");
    expect(content).toContain("PORT=3000");
    expect(content).toContain("SENSITIVE");
    expect(content).not.toContain("DB_PASSWORD=");
  });
});

describe("Docs command output generation", () => {
  test("generates markdown documentation from schema", () => {
    const schema: SchemaDefinition = {
      API_KEY: {
        type: "string",
        required: true,
        sensitive: true,
        docs: "Your API authentication key",
      },
      PORT: {
        type: "port",
        default: 3000,
        docs: "HTTP server port",
      },
    };

    const lines: string[] = [];
    lines.push("# Environment Variables");
    lines.push("");

    for (const [key, rule] of Object.entries(schema)) {
      lines.push(`## ${key}`);
      if (rule.docs) lines.push(`${rule.docs}`);
      lines.push(`- **Type:** \`${rule.type}\``);
      if (rule.required) lines.push("- **Required:** Yes");
      if (rule.default !== undefined)
        lines.push(`- **Default:** \`${rule.default}\``);
      if (rule.sensitive) lines.push("- **Sensitive:** Yes");
      lines.push("");
    }

    const content = lines.join("\n");
    expect(content).toContain("## API_KEY");
    expect(content).toContain("Your API authentication key");
    expect(content).toContain("**Sensitive:** Yes");
    expect(content).toContain("## PORT");
    expect(content).toContain("**Default:** `3000`");
  });
});
