// Auto-generated by dotenv-guard

/// <reference types="vite/client" />

declare namespace NodeJS {
  interface ProcessEnv {
    readonly VITE_APP_TITLE: string;
    readonly VITE_API_URL: string;
    readonly VITE_DEBUG_MODE: boolean;
    readonly VITE_MAX_ITEMS: number;
  }
}

interface ImportMetaEnv {
  readonly VITE_APP_TITLE: string;
  readonly VITE_API_URL: string;
  readonly VITE_DEBUG_MODE: boolean;
  readonly VITE_MAX_ITEMS: number;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
