import { Command } from "commander";
import chalk from "chalk";
import ora from "ora";
import { writeFileSync } from "fs";
import { loadSchema } from "./utils.js";
import { SchemaRule } from "../../index.js";

export default function (_program: Command) {
  return new Command("sync")
    .description("Generate/update .env.example file")
    .option("--output <file>", "Output file path", ".env.example")
    .action(async (options, command) => {
      const rootOpts = command.parent.opts();
      const spinner = ora("Generating .env.example.......").start();

      try {
        const schema = await loadSchema(rootOpts.schema);

        if (!schema || typeof schema !== "object") {
          throw new Error(`The schema loaded from "${rootOpts.schema}" is not valid.`);
        }

        const parts: string[] = ["# Auto-generated by dotenv-gad\n\n"];

        Object.entries(schema).forEach(([key, rule]) => {
          if ((rule as SchemaRule).sensitive) return;

          const eff = rule as SchemaRule;

          // If this is a grouped object with properties, emit grouped entries
          if (eff.type === "object" && eff.properties) {
            const prefix = eff.envPrefix || `${key}_`;
            parts.push(`# ${eff.docs || "No description available"}\n`);
            parts.push(`# Group: ${key} (prefix=${prefix})\n`);

            Object.entries(eff.properties).forEach(([prop, pRule]) => {
              const pr = pRule as SchemaRule;
              if (pr.sensitive) return;
              parts.push(`# ${pr.docs || "No description available"}\n`);
              parts.push(`# Type: ${pr.type}\n`);
              if (pr.default !== undefined) {
                parts.push(`# Default: ${JSON.stringify(pr.default)}\n`);
              }
              parts.push(`${prefix}${prop}=${pr.default ? JSON.stringify(pr.default) : ""}\n\n`);
            });

            return;
          }

          parts.push(`# ${eff.docs || "No description available"}\n`);
          parts.push(`# Type: ${eff.type}\n`);
          if (eff.default !== undefined) {
            parts.push(`# Default: ${JSON.stringify(eff.default)}\n`);
          }
          parts.push(`${key}=${eff.default ? JSON.stringify(eff.default) : ""}\n\n`);
        });

        writeFileSync(options.output, parts.join("").trimEnd());
        spinner.succeed(chalk.green(`Generated ${options.output} successfully!`));
      } catch (error) {
        spinner.fail(chalk.red(`Failed to generate .env.example`));
        console.error(chalk.yellow((error as Error).message));
        process.exit(1);
      }
    });
}
