import { Command } from "commander";
import chalk from "chalk";
import ora from "ora";
import { writeFileSync } from "fs";
import { loadSchema } from "./utils";
import { SchemaRule } from "../../schema";

function getTypeForRule(rule: SchemaRule): string {
  switch (rule.type) {
    case "number":
    case "port":
      return "number";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    case "array":
      return rule.items ? `${getTypeForRule(rule.items)}[]` : "any[]";
    case "object":
    case "json":
      return "Record<string, any>";
    case "string":
    case "email":
    case "url":
    case "ip":
    default:
      return "string";
  }
}

export default function (program: Command) {
  return new Command("types")
    .description("Generate Typescript types")
    .option("--output <file>", "Output file path", "env.d.ts")
    .action(async (options, command) => {
      const rootOpts = command.parent.opts();
      const spinner = ora("Generating type definitions.......").start();

      try {
        const schema = await loadSchema(rootOpts.schema);
        let typeContent =
          "// Auto-generated by dotenv-gad\n\ndeclare namespace NodeJS{\n  interface ProcessEnv{\n";

        Object.entries(schema).forEach(([key, rule]) => {
          const schemaRule = rule as SchemaRule;
          let type: string;

          switch (schemaRule.type) {
            case "number":
            case "port":
              type = "number";
              break;
            case "boolean":
              type = "boolean";
              break;
            case "date":
              type = "Date";
              break;
            case "array":
              if (schemaRule.items) {
                const itemType = getTypeForRule(schemaRule.items);
                type = `${itemType}[]`;
              } else {
                type = "any[]";
              }
              break;
            case "object":
            case "json":
              type = "Record<string, any>";
              break;
            case "string":
            case "email":
            case "url":
            case "ip":
            default:
              type = "string";
          }

          if (schemaRule.enum) {
            type = schemaRule.enum.map((v) => JSON.stringify(v)).join(" | ");
          }

          typeContent += `    ${key}${
            schemaRule.required ? "" : "?"
          }: ${type};\n`;
        });

        typeContent += "  }\n}\n";

        writeFileSync(options.output, typeContent);
        spinner.succeed(
          chalk.green(`Generated ${options.output} successfully!`)
        );
      } catch (error) {
        spinner.fail(chalk.red("Failed to generate type definitions"));
        console.error(error);
        process.exit(1);
      }
    });
}
